spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

fitify:
  cors:
    allowed-origins: ${FITIFY_CORS_ALLOWED_ORIGINS}

logging:
  level:
    com.nickdferrara.fitify: INFO
    org.springframework.modulith: INFO
